name: "ibbot-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "2523ASDF#$@"

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/bot/*.log
    fields:
      - service: ibbot
    fields_under_root: true
    json:
      keys_under_root: true
      overwrite_keys: true
      message_key: 'message'
  - type: log
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    fields:
      log_type: docker_error
    fields_under_root: true
output.elasticsearch:
  index: "ibbot-%{+yyyy.MM.dd}"
  when.contains:
    fields.service: "ibbot"

  index: "docker-%{+yyyy.MM.dd}"
  when.contains:
    fields.log_type: "docker_error"
